### ISSUE TITLE
Backend Project Scaffolding

### ISSUE THREAD

**Issue by timizuoebideri1** [fidepad/repo-automator#1]
# Summary

## Linters and Formatters
We would be using this libraries for linting and formatting:

- black
- flake8
- pylint
- docformatter
- isort

## Task automation
Using Makefile create automated cli commands, for example `make start` should spin up all docker container needed to start the project

## Acceptance Criteria 
- [x] Setup project using Django, DRF, Docker and Docker compose.
- [x] Setup authentication using [Knox](https://james1345.github.io/django-rest-knox/).
- [x] Database Postgres on docker.
- [x] API documentation using [drf-spectacular](https://pypi.org/project/drf-spectacular/)
- [x] Unittest
- [x] Linting Test
- [x] Formaters Test
